export const categories = [
  {
    name: "foodAndBeverage",
    label: "Food & Beverage",
    text: "Food &<br />Beverage",
    mobileText: "Food &<br />Beverage",
    src: "https://ik.imagekit.io/a1fr3d10/cubimart/food_and_beverage.svg",
  },
  {
    name: "toysAndBabyProducts",
    label: "Toys & Baby Products",
    text: "Toys & Baby<br />Products",
    mobileText: "Baby<br />Products",
    src: "https://ik.imagekit.io/a1fr3d10/cubimart/toys_and_baby_products.svg",
  },
  {
    name: "kidsFashion",
    label: "Kids' Fashion",
    text: "Kids'<br />Fashion",
    mobileText: "Kids'<br />Fashion",
    src: "https://ik.imagekit.io/a1fr3d10/cubimart/kids_fashion.svg",
  },
  {
    name: "videoGamesAndHobbies",
    label: "Video Games & Hobbies",
    text: "Video Games &<br />Hobbies",
    mobileText: "Games &<br />Hobbies",
    src: "https://ik.imagekit.io/a1fr3d10/cubimart/video_games_and_hobbies.svg",
  },
  {
    name: "sportsAndOutdoors",
    label: "Sports & Outdoors",
    text: "Sports &<br />Outdoors",
    mobileText: "Sports &<br />Outdoors",
    src: "https://ik.imagekit.io/a1fr3d10/cubimart/sports_and_outdoors.svg",
  },
  {
    name: "multimediaAndEntertainment",
    label: "Multimedia & Entertainment",
    text: "Multimedia &<br />Entertainment",
    mobileText: "Multimedia &<br />Entertainment",
    src: "https://ik.imagekit.io/a1fr3d10/cubimart/multimedia_and_entertainment.svg",
  },
  {
    name: "electronicsAndGadgets",
    label: "Electronics & Gadgets",
    text: "Electronics &<br />Gadgets",
    mobileText: "IT &<br />Gadgets",
    src: "https://ik.imagekit.io/a1fr3d10/cubimart/electronics_and_gadgets.svg",
  },
  {
    name: "petsSupplies",
    label: "Pets' Supplies",
    text: "Pets'<br />Supplies",
    mobileText: "Pets'<br />Supplies",
    src: "https://ik.imagekit.io/a1fr3d10/cubimart/pet_supplies.svg",
  },
  {
    name: "mensApparel",
    label: "Men's Apparel",
    text: "Men's<br />Apparel",
    mobileText: "Men's<br />Apparel",
    src: "https://ik.imagekit.io/a1fr3d10/cubimart/men_apparel.svg",
  },
  {
    name: "womensApparel",
    label: "Women's Apparel",
    text: "Women's<br />Apparel",
    mobileText: "Women's<br />Apparel",
    src: "https://ik.imagekit.io/a1fr3d10/cubimart/women_apparel.svg",
  },
  {
    name: "accessoriesAndJewellery",
    label: "Accessories & Jewellery",
    text: "Accessories &<br/>Jewellery",
    mobileText: "Jewellery",
    src: "https://ik.imagekit.io/a1fr3d10/cubimart/accessories_and_jewellery.svg",
  },
  {
    name: "miscellaneousOrOthers",
    label: "Miscellaneous / Others",
    text: "Miscellaneous /<br />Others",
    mobileText: "Others",
    src: "https://ik.imagekit.io/a1fr3d10/cubimart/miscellaneous.svg",
  },
];
